name: "ghav human: Test"
"on":
  push:
    branches:
      - ghav/dev/19435
    paths:
      - .ghav/human
permissions: {}
jobs:
  e2e-tests-web:
    name: End-to-End Tests (Web)
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./e2e
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version-file: ./e2e/.nvmrc
      - name: Run setup typescript-sdk
        run: npm ci && npm run build
        working-directory: ./open-api/typescript-sdk
        if: ${{ !cancelled() }}
      - name: Install dependencies
        run: npm ci
        if: ${{ !cancelled() }}
      - name: Install Playwright Browsers
        run: npx playwright install chromium --only-shell
        if: ${{ !cancelled() }}
      - name: Docker build
        run: docker compose build
        if: ${{ !cancelled() }}
      - name: Run e2e tests (web)
        run: npx playwright test
        if: ${{ !cancelled() }}
